base_url = "https://alex-song.com"
title = "Alex Song"
description = "Blog tracking daily learning"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
theme = "apollo"
taxonomies = [{ name = "tags" }, { name = "categories" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/not-matthias/apollo/tree/main/content/"

fediverse = false    # author attribution
fediverse_creator = ""    # e.g. @user@instance

menu = [
    { name = "Posts", url = "/posts", weight = 1 },
    { name = "Tags", url = "/tags", weight = 1 },
    { name = "Categories", url = "/categories", weight = 1 },
    { name = "Archives", url = "/archives", weight = 1 },
    { name = "Books", url = "/books", weight = 2 },
]

socials = [
    { name = "mail", url = "mailto:logensong@gmail.com", icon = "email" },
    { name = "github", url = "https://github.com/ljsong/", icon = "github" },
]

stylesheets = [
    # "custom.css"    # at /static/custom.css
]

[extra.taxonomies]
sort_by = "page_count"         # e.g. name, page_count
reverse = true

[extra.analytics]
enabled = false